/******************************************************************************
This file is part of the lemmagen library. It gives support for lemmatization.
Copyright (C) 2011 Jernej Virag <jernej@virag.si>

The lemmagen library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class si_virag_lemmatizer_SlLemmatizer */

#ifndef _Included_si_virag_lemmatizer_SlLemmatizer
#define _Included_si_virag_lemmatizer_SlLemmatizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     si_virag_lemmatizer_SlLemmatizer
 * Method:    loadLanguageLibrary
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_si_virag_lemmatizer_SlLemmatizer_loadLanguageLibrary
  (JNIEnv *, jobject, jstring);

/*
 * Class:     si_virag_lemmatizer_SlLemmatizer
 * Method:    lemmatize
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_si_virag_lemmatizer_SlLemmatizer_lemmatize
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
