/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class si_virag_lemmatizer_SlLemmatizer */

#ifndef _Included_si_virag_lemmatizer_SlLemmatizer
#define _Included_si_virag_lemmatizer_SlLemmatizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     si_virag_lemmatizer_SlLemmatizer
 * Method:    loadLanguageLibrary
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_si_virag_lemmatizer_SlLemmatizer_loadLanguageLibrary
  (JNIEnv *, jobject, jstring);

/*
 * Class:     si_virag_lemmatizer_SlLemmatizer
 * Method:    lemmatize
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_si_virag_lemmatizer_SlLemmatizer_lemmatize
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
