#ifndef FLEX_HEADER_header_RdrLexer_h
#define FLEX_HEADER_header_RdrLexer_h
#define YY_Lexer_CHAR unsigned char
#line 1 "Q:\\01 Dokumenti\\IJS\\Projects\\LemmaGen\\support\\lex-bison\\binary\\win32\\flex\\flexskel.h"
/* A lexical scanner header generated by flex */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */


/*********************************************/
/* SYSTEM dependent declaration, includes... */
/*********************************************/
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
#ifdef __cplusplus
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
#else	/* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#else
#endif	/* __GNUC__ */
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#endif	/* __STDC__ */
#endif	/* ! __cplusplus */
/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif
#include <stdio.h>




/* % here is the declaration from section1 %header{  */ 
#line 23 "definition\\RdrLexer.def"
#define YY_Lexer_CLASS  RdrLexer    
#line 25 "definition\\RdrLexer.def"
#define YY_Lexer_IOSTREAM 
#line 27 "definition\\RdrLexer.def"
#define YY_Lexer_MEMBERS  \
		public: \
		private: \
			int iLine; \
			int iColm; \
			YY_Parser_STYPE *uStxVal; \
			void debugPrt(const char *acToken, unsigned const char *acText, \
			         const char *acOldState, const char *acNewState, \
			         const char *acReturn);
#line 37 "definition\\RdrLexer.def"
#define YY_Lexer_CONSTRUCTOR_PARAM  YY_Parser_STYPE *YY_Parser_LVAL, \
						  YY_Parser_LTYPE *YY_Parser_LLOC
#line 39 "definition\\RdrLexer.def"
#define YY_Lexer_CONSTRUCTOR_CODE  \
		iLine = 1; \
		iColm = 0; \
		uStxVal = YY_Parser_LVAL; \
		YY_Parser_LLOC->piLine = &iLine; \
		YY_Parser_LLOC->piColm = &iColm; \
		YY_Parser_LLOC->piLeng = &yyleng; \
		YY_Parser_LLOC->pacText = &yytext; \
		BEGIN COMMENT;
#line 50 "definition\\RdrLexer.def"
#define YY_Lexer_LEX_RETURN  RdrParser::YY_Parser_ENUM_TOKEN
#line 51 "definition\\RdrLexer.def"
#define YY_Lexer_LEX  yylex_lexer
#line 54 "definition\\RdrLexer.def"
	#include "../header/RdrParser.h"

	#define YY_USER_ACTION DBGPRT iColm +=yyleng;
	#undef yyterminate
	#define yyterminate() return RdrParser::EOFNULL	
#line 134 "definition\\RdrLexer.def"
#line 52 "Q:\\01 Dokumenti\\IJS\\Projects\\LemmaGen\\support\\lex-bison\\binary\\win32\\flex\\flexskel.h"

#ifdef YY_USE_CLASS
#ifdef YY_Lexer_IOSTREAM
#include <iostream>
#define YY_Lexer_IFILE  istream
#define YY_Lexer_OFILE ostream 
#define YY_Lexer_ERRFILE cerr

#ifndef YY_Lexer_IFILE_DEFAULT
#define YY_Lexer_IFILE_DEFAULT &cin
#endif

#ifndef YY_Lexer_OFILE_DEFAULT
#define YY_Lexer_OFILE_DEFAULT &cout
#endif

#endif
#endif

#ifndef YY_Lexer_IFILE
#define YY_Lexer_IFILE FILE 
#endif

#ifndef YY_Lexer_OFILE
#define YY_Lexer_OFILE FILE 
#endif

#ifndef YY_Lexer_ERRFILE
#define YY_Lexer_ERRFILE stderr
#endif

#ifndef YY_Lexer_IFILE_DEFAULT
#define YY_Lexer_IFILE_DEFAULT stdin
#endif

#ifndef YY_Lexer_OFILE_DEFAULT
#define YY_Lexer_OFILE_DEFAULT stdout
#endif




#ifndef YY_Lexer_TEXT
#define YY_Lexer_TEXT yytext
#endif
#ifndef YY_Lexer_LENG
#define YY_Lexer_LENG yyleng
#endif
#ifndef YY_Lexer_IN
#define YY_Lexer_IN yyin
#endif
#ifndef YY_Lexer_OUT
#define YY_Lexer_OUT yyout
#endif

#ifndef YY_Lexer_LEX_RETURN
#define YY_Lexer_LEX_RETURN int
#else
#ifndef YY_Lexer_LEX_DEFINED
#define YY_Lexer_LEX_DEFINED 
#endif
#endif

#ifndef YY_Lexer_LEX
#define YY_Lexer_LEX yylex
#else
#ifndef YY_Lexer_LEX_DEFINED
#define YY_Lexer_LEX_DEFINED 
#endif
#endif

#ifndef YY_Lexer_LEX_PARAM
#ifndef YY_USE_PROTOS
#define YY_Lexer_LEX_PARAM 
#else
#define YY_Lexer_LEX_PARAM void
#endif
#else
#ifndef YY_Lexer_LEX_DEFINED
#define YY_Lexer_LEX_DEFINED 
#endif
#endif

#ifndef YY_Lexer_LEX_PARAM_DEF
#define YY_Lexer_LEX_PARAM_DEF
#else
#ifndef YY_Lexer_LEX_DEFINED
#define YY_Lexer_LEX_DEFINED 
#endif
#endif

#ifndef YY_Lexer_RESTART
#define YY_Lexer_RESTART yyrestart
#endif
#ifndef YY_Lexer_SWITCH_TO_BUFFER
#define YY_Lexer_SWITCH_TO_BUFFER yy_switch_to_buffer
#endif
#ifndef YY_Lexer_LOAD_BUFFER_STATE
#define YY_Lexer_LOAD_BUFFER_STATE yy_load_buffer_state
#endif

#ifndef YY_Lexer_CREATE_BUFFER
#define YY_Lexer_CREATE_BUFFER yy_create_buffer
#ifndef YY_USE_CLASS
#ifndef yy_new_buffer
#define yy_new_buffer yy_create_buffer
#endif
#endif
#endif
#ifndef YY_Lexer_DELETE_BUFFER
#define YY_Lexer_DELETE_BUFFER yy_delete_buffer
#endif
#ifndef YY_Lexer_INIT_BUFFER
#define YY_Lexer_INIT_BUFFER yy_init_buffer
#endif



#ifdef YY_Lexer_FLEX_DEBUG
#ifndef YY_Lexer_DEBUG
#define YY_Lexer_DEBUG 1
#endif
#else
#ifndef YY_Lexer_DEBUG
#define YY_Lexer_DEBUG 0
#endif
#endif

#if YY_Lexer_DEBUG != 0
#ifndef YY_Lexer_DEBUG_FLAG
#define YY_Lexer_DEBUG_FLAG yy_flex_debug
#endif
#ifndef YY_Lexer_DEBUG_INIT
#define YY_Lexer_DEBUG_INIT 1
#endif
#endif




#ifndef YY_USE_CLASS
#ifndef YY_Lexer_CURRENT_BUFFER
#define YY_Lexer_CURRENT_BUFFER yy_current_buffer
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern void YY_Lexer_RESTART YY_PROTO(( YY_Lexer_IFILE *input_file ));
extern void YY_Lexer_SWITCH_TO_BUFFER YY_PROTO(( YY_BUFFER_STATE new_buffer ));
extern void YY_Lexer_LOAD_BUFFER_STATE YY_PROTO(( void ));
extern YY_BUFFER_STATE YY_Lexer_CREATE_BUFFER YY_PROTO(( YY_Lexer_IFILE *file, int size ));
extern void YY_Lexer_DELETE_BUFFER YY_PROTO(( YY_BUFFER_STATE b ));
extern void YY_Lexer_INIT_BUFFER YY_PROTO(( YY_BUFFER_STATE b, YY_Lexer_IFILE *file ));

#if YY_Lexer_DEBUG != 0
extern int YY_Lexer_DEBUG_FLAG ;
#endif
extern YY_Lexer_CHAR  *YY_Lexer_TEXT;
extern int YY_Lexer_LENG;
extern YY_Lexer_IFILE *YY_Lexer_IN;
extern YY_Lexer_OFILE *YY_Lexer_OUT;
#ifdef YY_Lexer_LEX_DEFINED
extern YY_Lexer_LEX_RETURN YY_Lexer_LEX ( YY_Lexer_LEX_PARAM )
YY_Lexer_LEX_PARAM_DEF
#else
#ifndef YY_DECL
extern YY_Lexer_LEX_RETURN YY_Lexer_LEX ( YY_Lexer_LEX_PARAM )
YY_Lexer_LEX_PARAM_DEF
#else
/* no declaration if oldstyle flex */
#endif
#endif
#else

#ifndef YY_Lexer_CURRENT_BUFFER
#define YY_Lexer_CURRENT_BUFFER YY_CURRENT_BUFFER
#endif
#ifndef YY_Lexer_CLASS
#define YY_Lexer_CLASS Lexer
#endif
#ifndef YY_Lexer_ECHO
#define YY_Lexer_ECHO yy_echo
#endif
#ifdef YY_Lexer_ECHO_PURE
#define YY_Lexer_ECHO_NOCODE
#endif

#ifndef YY_Lexer_ECHO_CODE
#ifndef YY_Lexer_IOSTREAM
#define YY_Lexer_ECHO_CODE fwrite( (char *) YY_Lexer_TEXT, YY_Lexer_LENG, 1, YY_Lexer_OUT );
#else
#define YY_Lexer_ECHO_CODE (YY_Lexer_OUT->write( (char *) YY_Lexer_TEXT, YY_Lexer_LENG));
#endif
#endif

#ifndef YY_Lexer_INPUT
#define YY_Lexer_INPUT yy_input
#endif
#ifdef YY_Lexer_INPUT_PURE
#define YY_Lexer_INPUT_NOCODE
#endif

#ifndef YY_Lexer_INPUT_CODE
#ifndef YY_Lexer_IOSTREAM
#define YY_Lexer_INPUT_CODE return result= fread(  buffer, 1,max_size,YY_Lexer_IN );
#else
#define YY_Lexer_INPUT_CODE if(YY_Lexer_IN->eof())  result=0;else {YY_Lexer_IN->read(buffer,max_size);result=YY_Lexer_IN->gcount();YY_Lexer_IN->clear(YY_Lexer_IN->rdstate()&(~ios::failbit));if(YY_Lexer_IN->bad()) result= -1;} return result;
#endif
#endif

#ifdef YY_Lexer_FATAL_ERROR_PURE
#define YY_Lexer_FATAL_ERRO_NOCODE
#endif
#ifndef YY_Lexer_FATAL_ERROR
#define YY_Lexer_FATAL_ERROR yy_fatal_error
#endif

#ifndef YY_Lexer_FATAL_ERROR_CODE
#ifndef YY_Lexer_IOSTREAM
#define YY_Lexer_FATAL_ERROR_CODE fputs( msg, YY_Lexer_ERRFILE );putc( '\n', YY_Lexer_ERRFILE );exit( 1 );
#else
#define YY_Lexer_FATAL_ERROR_CODE YY_Lexer_ERRFILE<< msg <<endl;exit( 1 );
#endif
#endif

#ifndef YY_Lexer_WRAP
#define YY_Lexer_WRAP yy_wrap
#endif
#ifdef YY_Lexer_WRAP_PURE
#define YY_Lexer_WRAP_NOCODE
#endif
#ifndef YY_Lexer_WRAP_CODE
#define YY_Lexer_WRAP_CODE return 1;
#endif


#ifndef YY_Lexer_INHERIT
#define YY_Lexer_INHERIT
#endif
#ifndef YY_Lexer_MEMBERS
#define YY_Lexer_MEMBERS 
#endif
#ifndef YY_Lexer_CONSTRUCTOR_PARAM
#define YY_Lexer_CONSTRUCTOR_PARAM
#endif
#ifndef YY_Lexer_CONSTRUCTOR_CODE
#define YY_Lexer_CONSTRUCTOR_CODE
#endif
#ifndef YY_Lexer_CONSTRUCTOR_INIT
#define YY_Lexer_CONSTRUCTOR_INIT
#endif
#ifndef YY_Lexer_DESTRUCTOR_CODE
#define YY_Lexer_DESTRUCTOR_CODE
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

class YY_Lexer_CLASS YY_Lexer_INHERIT
{
 private:/* data */
 YY_Lexer_CHAR  *yy_c_buf_p;
 YY_Lexer_CHAR  yy_hold_char;
 int yy_n_chars;
 int yy_init;
 int yy_start;
 int yy_did_buffer_switch_on_eof;
 private: /* functions */
 void yy_initialize();
 int input();
 int yyinput() {return input();};
 int yy_get_next_buffer();
 void yyunput( YY_Lexer_CHAR  c, YY_Lexer_CHAR  *buf_ptr );
 /* use long instead of yy_state_type because it is undef */
 long yy_get_previous_state_ ( void );
 long yy_try_NUL_trans_  ( long current_state_ );
 protected:/* non virtual */
 YY_BUFFER_STATE YY_Lexer_CURRENT_BUFFER;
 void YY_Lexer_RESTART ( YY_Lexer_IFILE *input_file );
 void YY_Lexer_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer );
 void YY_Lexer_LOAD_BUFFER_STATE( void );
 YY_BUFFER_STATE YY_Lexer_CREATE_BUFFER( YY_Lexer_IFILE *file, int size );
 void YY_Lexer_DELETE_BUFFER( YY_BUFFER_STATE b );
 void YY_Lexer_INIT_BUFFER( YY_BUFFER_STATE b, YY_Lexer_IFILE *file );
 protected: /* virtual */
 virtual void YY_Lexer_ECHO()
#ifdef YY_Lexer_ECHO_PURE
  =0
#endif
  ;
 virtual int  YY_Lexer_INPUT(char  *buf,int &result,int max_size)
#ifdef YY_Lexer_INPUT_PURE
  =0
#endif
  ;
 virtual void  YY_Lexer_FATAL_ERROR(char *msg)
#ifdef YY_Lexer_FATAL_ERROR_PURE
  =0
#endif
  ;
 virtual int  YY_Lexer_WRAP()
#ifdef YY_Lexer_WRAP_PURE
  =0
#endif
  ;
 public:
 YY_Lexer_CHAR  *YY_Lexer_TEXT;
 int YY_Lexer_LENG;
 YY_Lexer_IFILE *YY_Lexer_IN;
 YY_Lexer_OFILE *YY_Lexer_OUT;
 YY_Lexer_LEX_RETURN YY_Lexer_LEX ( YY_Lexer_LEX_PARAM);
 YY_Lexer_CLASS(YY_Lexer_CONSTRUCTOR_PARAM) ;
 virtual ~YY_Lexer_CLASS() ;
#if YY_Lexer_DEBUG != 0
 int YY_Lexer_DEBUG_FLAG;
#endif
 public: /* added members */
 YY_Lexer_MEMBERS 
};
#endif



/* declaration of externs for public use of yylex scanner */

/* % here is the declaration from section2 %header{ */ 
#line 168 "definition\\RdrLexer.def"
#endif
#line 375 "Q:\\01 Dokumenti\\IJS\\Projects\\LemmaGen\\support\\lex-bison\\binary\\win32\\flex\\flexskel.h"

/* end of generated header */
