#define YY_CHAR unsigned char
#line 1 "Q:\\01 Dokumenti\\IJS\\Projects\\LemmaGen\\support\\lex-bison\\binary\\win32\\flex\\flexskel.cc"
//Added by MJ for compatibility with VisualStudio2005 Compiler
#define _MSDOS

/* A lexical scanner generated by flex */
/* scanner skeleton version:
 * $Header: c:\\Program\040Files\\Development\\CVS\040Repository/flex++/flexskel.cc,v 1.1.1.1 2002/04/13 06:01:32 Bear Exp $
 */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */
/* institutional financial group  */

/* theses symbols are added before this file */
/* #define YY_CHAR 'unsigned char' if 8bit or 'char' if 7bit */
/* #define FLEX_DEBUG if debug mode */
#define FLEX_SCANNER
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
/* Old MSC, before c7 */
#ifdef MSDOS
#ifndef _MSDOS
#define _MSDOS
#endif
#endif
/* turboc */
#ifdef __MSDOS__
#ifndef _MSDOS
#define _MSDOS
#endif
#endif

#ifdef __cplusplus
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
#ifndef _MSDOS
#include <osfcn.h>
#endif
#else   /* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
int read();
#else
#include <stdlib.h>
#endif  /* __GNUC__ */
#define YY_USE_PROTOS
#define YY_USE_CONST
#endif  /* __STDC__ */
#endif  /* ! __cplusplus */
#ifdef __TURBOC__
#define YY_USE_CONST
#endif
#include <stdio.h>


/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
/* the "const" storage-class-modifier is valid */
#ifndef YY_USE_CONST
#define const
#endif
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif


/*********************/
/* parameters        */

/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif
/* size of default input buffer */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) 
#endif

/***********************************/
/* to be redefined for application */

/* returned upon end-of-file */
#define YY_END_TOK 0
/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* code executed at the end of each rule */
#define YY_BREAK break;

/* #define YY_USER_ACTION */
/* #define YY_USER_INIT */


#ifndef YY_USE_CLASS
/* copy whatever the last rule matched to the standard output */
/* cast to (char *) is because for 8-bit chars, yy___text is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yy___text, yy___leng, 1, yy___out )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifdef _MSDOS
#define YY_INPUT(buf,result,max_size) \
	if ( (result = fread(buf,1,max_size,yy___in)) < 0 ) \
	    YY_FATAL_ERROR( "fread() in flex scanner failed" );
#else
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yy___in), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );

#endif
/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 *      if ( something_happens )
 *              YY_FATAL_ERROR( "oops, the something happened" );
 *      else
 *              everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, yy___stderr  ); \
		(void) putc( '\n', yy___stderr  ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1


/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 
#else 
/* c++ */
#define ECHO yy___echo()
#define YY_INPUT(buf,result,max_size) \
	if ( yy___input((char *)buf, result,max_size) < 0 ) \
	    YY_FATAL_ERROR( "YY_INPUT() in flex scanner failed" );

#define YY_FATAL_ERROR(msg) yy___fatal_error(msg)
#define yywrap() yy___wrap()

#endif
/***********************************/
/* not to be changed */
#define YY_NULL 0
#define YY_END_OF_BUFFER_CHAR 0
/* special action meaning "start processing a new file" */
#define YY_NEW_FILE yy___newfile 
/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)



/* % section 1 definitions go here */ 
#line 1 "definition\\RdrLexer.def"
#define INITIAL 0
/******************************************************************************
This file is part of the lemmagen library. It gives support for lemmatization.
Copyright (C) 2006-2007 Matjaz Jursic <matjaz@gmail.com>

The lemmagen library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
******************************************************************************/
#define YY_Lexer_FLEX_SCANNER
#line 62 "definition\\RdrLexer.def"
	//#define DBG
	#ifdef DBG	
		char *dbgTbl[][4] =
				{{"", "?-1", "", ""},
				{"Comment", "COMMENT", "", "NO RETURN"},
				{"Rule", "COMMENT", "RULE", "RULE_START"},
				{"ExcStart", "COMMENT", "RULE", "EXC_START"},
				{"ExcEnd", "COMMENT", "RULE", "EXC_END"},
				{"NewLine", "COMMENT", "", "NO RETURN"},
				{"<<EOF>>", "COMMENT", "", "EOFNULL"},
				{"Id", "RULE", "", "ID"},
				{"If", "RULE", "", "IF"},
				{"Then", "RULE", "", "THEN"},
				{"Exc", "RULE", "", "EXC"},
				{"Lbrac", "RULE", "", "LBRAC"},
				{"Rbrac", "RULE", "", "RBRAC"},
				{"Transf", "RULE", "", "TRANSF"},
				{"WhtSpcChar", "RULE", "", "NO RETURN"},
				{"StrConst", "RULE", "", "STRING"},
				{"ChrConst", "RULE", "", "STRING"},
				{"DecConst", "RULE", "", "INT"},
				{"Semicol", "RULE", "COMMENT", "RULE_END"},
				{"NewLine", "RULE", "COMMENT", "RULE_END"},
				{"EOF",  "RULE", "COMMENT", "RULE_END"},
				{".Any", "RULE", "", "ERROR"},
				{"", "?+1", "", ""},
				{"", "?+2", "", ""}};	
		#define DBGPRT debugPrt(dbgTbl[yy_act][0], yytext, dbgTbl[yy_act][1], dbgTbl[yy_act][2], dbgTbl[yy_act][3]);
	#else
		#define DBGPRT
		
	#endif	
#define COMMENT 1
#define RULE 2
#include "../header/RdrLexer.h"
#line 134 "definition\\RdrLexer.def"
#line 199 "Q:\\01 Dokumenti\\IJS\\Projects\\LemmaGen\\support\\lex-bison\\binary\\win32\\flex\\flexskel.cc"

#define yy___stderr YY_Lexer_ERRFILE
#define yy___text YY_Lexer_TEXT
#define yy___leng YY_Lexer_LENG
#define yy___in YY_Lexer_IN
#define yy___out YY_Lexer_OUT
#define yy___newfile \
	do \
		{ \
		YY_Lexer_INIT_BUFFER( YY_Lexer_CURRENT_BUFFER, yy___in ); \
		YY_Lexer_LOAD_BUFFER_STATE(); \
		} \
	while ( 0 )
#if YY_Lexer_DEBUG != 0
#define yy___flex_debug YY_Lexer_DEBUG_FLAG
#endif


#ifdef YY_USE_CLASS

#define yy___echo YY_Lexer_ECHO
#define yy___input YY_Lexer_INPUT
#define yy___fatal_error YY_Lexer_FATAL_ERROR
#define yy___wrap YY_Lexer_WRAP

#endif

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yy___text
 */
#define YY_DO_BEFORE_ACTION \
	yy___text = yy_bp; \
/* % code to fiddle yy___text and yy___leng for yymore() goes here */ \
	yy___leng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yy___text */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yy___text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yy___text )



struct yy_buffer_state
    {
    YY_Lexer_IFILE  *yy_input_file;

    YY_Lexer_CHAR *yy_ch_buf;               /* input buffer */
    YY_Lexer_CHAR *yy_buf_pos;      /* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters */
    int yy_buf_size;    

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;          /* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */

#ifndef YY_USE_CLASS

#if YY_Lexer_DEBUG != 0
int YY_Lexer_DEBUG_FLAG=YY_Lexer_DEBUG_INIT;
#endif
#define YY_CURRENT_BUFFER YY_Lexer_CURRENT_BUFFER
static YY_BUFFER_STATE YY_Lexer_CURRENT_BUFFER;
/* yy_hold_char holds the character lost when yy___text is formed */
static YY_Lexer_CHAR yy_hold_char;

static int yy_n_chars;          /* number of characters read into yy_ch_buf */

/* GLOBAL */
YY_Lexer_CHAR *yy___text;
int yy___leng;

YY_Lexer_IFILE  *yy___in = (YY_Lexer_IFILE  *) 0;
YY_Lexer_OFILE *yy___out = (YY_Lexer_OFILE  *) 0;

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_Lexer_CHAR *yy_c_buf_p = (YY_Lexer_CHAR *) 0;
static int yy_init = 1;         /* whether we need to initialize */
static int yy_start = 0;        /* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yy___in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_Lexer_CHAR c, YY_Lexer_CHAR *buf_ptr ));

#else
/* c++ */
#ifndef YY_Lexer_ECHO_NOCODE
void YY_Lexer_CLASS::yy___echo()
{YY_Lexer_ECHO_CODE
}
#endif
#ifndef YY_Lexer_INPUT_NOCODE
int  YY_Lexer_CLASS::yy___input(char * buffer,int &result,int max_size)
{YY_Lexer_INPUT_CODE
}
#endif
#ifndef YY_Lexer_FATAL_ERROR_NOCODE
void YY_Lexer_CLASS::yy___fatal_error(char *msg)
{YY_Lexer_FATAL_ERROR_CODE
}
#endif
#ifndef YY_Lexer_WRAP_NOCODE
int  YY_Lexer_CLASS::yy___wrap()
{YY_Lexer_WRAP_CODE
}
#endif
void YY_Lexer_CLASS::yy_initialize()
{
 yy___in=0;yy___out=0;yy_init = 1;
 yy_start=0;
 yy___text=0;yy___leng=0;
 YY_Lexer_CURRENT_BUFFER=0;
 yy_did_buffer_switch_on_eof=0;
 yy_c_buf_p=0;yy_hold_char=0;yy_n_chars=0;
#if YY_Lexer_DEBUG != 0
 YY_Lexer_DEBUG_FLAG=YY_Lexer_DEBUG_INIT;
#endif
}

YY_Lexer_CLASS::YY_Lexer_CLASS(YY_Lexer_CONSTRUCTOR_PARAM) YY_Lexer_CONSTRUCTOR_INIT
{yy_initialize();
 YY_Lexer_CONSTRUCTOR_CODE;
}
YY_Lexer_CLASS::~YY_Lexer_CLASS() 
{YY_Lexer_DESTRUCTOR_CODE;
 if(YY_Lexer_CURRENT_BUFFER)
  YY_Lexer_DELETE_BUFFER(YY_Lexer_CURRENT_BUFFER);
}

#endif


#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

/* % data tables for the DFA go here */ 
#define YY_END_OF_BUFFER 24
typedef int yy_state_type;
static const short int yy_accept[105] =
    {   0,
        0,    0,    1,    1,   15,   15,   24,   23,    1,    5,
        5,    1,    1,    1,   22,   15,   20,   20,   22,   22,
       12,   13,   22,   18,   19,   10,    8,    7,   22,   22,
        9,    1,    5,    4,    0,    3,   15,   20,    0,   16,
        0,    0,   17,    0,    0,   14,   18,    0,   11,    0,
        7,    8,    0,    0,    0,    0,    0,    0,   18,    8,
        0,    0,   10,    0,    0,    8,    0,    0,    0,   18,
        0,    0,    0,    0,    0,    0,    9,    0,    2,   18,
        0,    0,   11,    0,    0,    0,    9,   18,    8,    0,
       10,    8,    0,   18,    0,    0,   18,    0,    0,   18,

        0,    9,   10,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    1,    1,    1,    1,    6,    7,
        8,    1,    1,    1,    9,    1,    1,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,    1,
        1,   22,    1,    1,   23,    1,   24,   25,   26,   27,
       28,   29,   30,    1,    1,   31,   32,   33,   34,   35,
        1,   36,   37,   38,   39,    1,   40,   41,    1,    1,
        1,   42,    1,    1,    1,    1,   23,    1,   24,   25,

       26,   27,   28,   29,   30,    1,    1,   31,   32,   33,
       34,   35,    1,   36,   37,   38,   39,    1,   40,   41,
        1,    1,   43,    1,   44,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[45] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    1,
        1,    1,    3,    1
    } ;

static const short int yy_base[110] =
    {   0,
        0,    0,    0,    2,   45,    0,  237,  238,    0,  238,
      233,  191,  195,  213,  238,  230,  238,  228,    2,   84,
      238,  238,    1,  117,  238,    0,    0,  207,  190,  189,
        1,    0,  238,  238,  196,  238,  224,  238,   95,  238,
      221,   96,  238,  220,    2,  238,  129,    1,  189,  198,
      238,  238,  189,  188,  189,   99,  101,   97,  139,   92,
       91,   84,   93,   92,   91,   89,   82,   81,   93,  149,
       79,   75,   85,   74,   78,   77,  238,   69,  238,  159,
       77,   78,  238,   65,   76,   58,   71,  169,  238,   57,
       66,  238,   61,  179,   60,   57,  189,   59,   59,  238,

        5,  238,  238,  238,  208,  211,    0,  214,  217
    } ;

static const short int yy_def[110] =
    {   0,
      105,  105,  106,  106,  104,    5,  104,  104,  107,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  108,  109,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  107,  104,  104,  104,  104,  104,  104,  108,  104,
      108,  109,  104,  109,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,

      104,  104,  104,    0,  104,  104,  104,  104,  104
    } ;

static const short int yy_nxt[283] =
    {   0,
       32,  104,   10,   11,   10,   11,   40,  104,  104,   45,
       45,  104,  104,  104,  104,  104,  104,  104,  104,   12,
      104,   12,   46,   46,   51,   60,   52,  104,  104,   56,
      104,  104,   48,  104,  104,   13,   57,   13,   61,   49,
       50,  103,   14,   41,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   15,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   15,   25,   15,   15,   15,   15,
       26,   15,   15,   15,   27,   15,   15,   28,   15,   15,
       29,   30,   31,   15,   15,   15,   15,   15,   15,   43,
      102,  101,   99,   98,   96,   95,   49,   93,   92,   40,

       51,   43,   91,   90,   89,   87,   86,   85,   84,   83,
       82,   81,   79,   78,   77,   76,   75,   51,   74,   73,
       72,   71,   69,   68,   67,   44,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   41,   44,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,  100,  100,

      100,  100,  100,  100,  100,  100,  100,  100,    8,    8,
        8,    9,    9,    9,   39,   66,   39,   42,   65,   42,
       64,   63,   62,   42,   39,   37,   58,   55,   54,   53,
       38,   37,   36,   35,   34,   33,  104,    7,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104
    } ;

static const short int yy_chk[283] =
    {   0,
      107,    0,    3,    3,    4,    4,   19,    0,    0,   23,
       45,    0,    0,    0,    0,    0,    0,    0,    0,    3,
        0,    4,   23,   45,   27,   48,   27,    0,    0,   31,
        0,    0,   26,    0,    0,    3,   31,    4,   48,   26,
       26,  101,    3,   19,    4,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,   20,
       99,   98,   96,   95,   93,   91,   90,   87,   86,   39,

       85,   42,   84,   82,   81,   78,   76,   75,   74,   73,
       72,   71,   69,   68,   67,   66,   65,   64,   63,   62,
       61,   60,   58,   57,   56,   20,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   39,   42,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   97,   97,

       97,   97,   97,   97,   97,   97,   97,   97,  105,  105,
      105,  106,  106,  106,  108,   55,  108,  109,   54,  109,
       53,   50,   49,   44,   41,   37,   35,   30,   29,   28,
       18,   16,   14,   13,   12,   11,    7,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

#if YY_Lexer_DEBUG != 0
static const short int yy_rule_linenum[23] =
    {   0,
      137,  138,  139,  140,  141,  141,  145,  146,  148,  149,
      150,  152,  153,  154,  156,  158,  159,  160,  162,  163,
      163,  166
    } ;

#endif
/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#line 379 "Q:\\01 Dokumenti\\IJS\\Projects\\LemmaGen\\support\\lex-bison\\binary\\win32\\flex\\flexskel.cc"
#ifndef YY_USE_CLASS
static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
#else
#define yy_get_previous_state() ((yy_state_type)(yy_get_previous_state_()))
#define yy_try_NUL_trans(c) ((yy_state_type)(yy_try_NUL_trans_(c)))
#endif

#ifndef YY_USE_CLASS
#ifdef YY_Lexer_LEX_DEFINED
YY_Lexer_LEX_RETURN YY_Lexer_LEX ( YY_Lexer_LEX_PARAM )
YY_Lexer_LEX_PARAM_DEF
#else
YY_DECL
#endif
#else
YY_Lexer_LEX_RETURN YY_Lexer_CLASS::YY_Lexer_LEX ( YY_Lexer_LEX_PARAM)

#endif
    {
    register yy_state_type yy_current_state;
    register YY_Lexer_CHAR *yy_cp, *yy_bp;
    register int yy_act;

/* % user's declarations go here */ 


	//--BEGLNCOMM-------------------------------------------------------------------------------------------
/* % end of prolog */ 
#line 404 "Q:\\01 Dokumenti\\IJS\\Projects\\LemmaGen\\support\\lex-bison\\binary\\win32\\flex\\flexskel.cc"

    if ( yy_init )
	{
	 
	 {
	 YY_USER_INIT;
	 }
	if ( ! yy_start )
	    yy_start = 1;       /* first start state */

	if ( ! yy___in )
	    yy___in = YY_Lexer_IFILE_DEFAULT;

	if ( ! yy___out )
	    yy___out = YY_Lexer_OFILE_DEFAULT;

	if ( YY_Lexer_CURRENT_BUFFER )
	    YY_Lexer_INIT_BUFFER( YY_Lexer_CURRENT_BUFFER, yy___in );
	else
	    YY_Lexer_CURRENT_BUFFER = YY_Lexer_CREATE_BUFFER( yy___in, YY_BUF_SIZE );

	YY_Lexer_LOAD_BUFFER_STATE();
	yy_init=0;
	}

    while ( 1 )         /* loops until end-of-file is reached */
	{
/* % yymore()-related code goes here */ 
#line 432 "Q:\\01 Dokumenti\\IJS\\Projects\\LemmaGen\\support\\lex-bison\\binary\\win32\\flex\\flexskel.cc"
	yy_cp = yy_c_buf_p;

	/* support of yy___text */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

/* % code to set up and find next match goes here */ 
	yy_current_state = yy_start;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 105 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 104 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;
#line 443 "Q:\\01 Dokumenti\\IJS\\Projects\\LemmaGen\\support\\lex-bison\\binary\\win32\\flex\\flexskel.cc"

yy_find_action:
/* % code to find the action number goes here */ 
	yy_act = yy_accept[yy_current_state];
#line 446 "Q:\\01 Dokumenti\\IJS\\Projects\\LemmaGen\\support\\lex-bison\\binary\\win32\\flex\\flexskel.cc"

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:      /* this label is used only to access EOF actions */
#if YY_Lexer_DEBUG != 0
	if ( yy___flex_debug )
		{
		if ( yy_act == 0 )
#ifndef YY_Lexer_IOSTREAM
			fprintf( yy___stderr , "--scanner backtracking\n" );
#else
			yy___stderr <<"--scanner backtracking"<<endl;
#endif
		else if ( yy_act < YY_END_OF_BUFFER -1 )
#ifndef YY_Lexer_IOSTREAM
			fprintf( yy___stderr , 
			 "--accepting rule at line %d (\"%s\")\n",
			 yy_rule_linenum[yy_act], yy___text );
#else
			yy___stderr <<"--accepting rule at line "
                          <<(int)yy_rule_linenum[yy_act]
                          <<" (\""<<(char *)yy___text<<"\")"<<endl;
#endif
		else if ( yy_act == YY_END_OF_BUFFER -1 )
#ifndef YY_Lexer_IOSTREAM
			fprintf( yy___stderr , 
			 "--accepting default rule (\"%s\")\n",
			 yy___text );
#else
			yy___stderr <<"--accepting default rule"
                          <<" (\""<<(char *)yy___text<<"\")"<<endl;
#endif
		else if ( yy_act == YY_END_OF_BUFFER )
#ifndef YY_Lexer_IOSTREAM
			fprintf( yy___stderr , "--(end of buffer or a NUL)\n" );
#else
			yy___stderr <<"--(end of buffer or a NUL)"<<endl;
#endif
		else
#ifndef YY_Lexer_IOSTREAM
			fprintf( yy___stderr , "--EOF\n" );
#else
			yy___stderr <<"--EOF"<<endl;
#endif
		}
#endif
	switch ( yy_act )
	    {
/* % actions go here */ 
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
#line 137 "definition\\RdrLexer.def"

	YY_BREAK
case 2:
#line 138 "definition\\RdrLexer.def"
BEGIN RULE; return RdrParser::RULE_START;
	YY_BREAK
case 3:
#line 139 "definition\\RdrLexer.def"
return RdrParser::EXC_START;
	YY_BREAK
case 4:
#line 140 "definition\\RdrLexer.def"
return RdrParser::EXC_END;
	YY_BREAK
case 5:
#line 141 "definition\\RdrLexer.def"
iLine++; iColm=1;
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 142 "definition\\RdrLexer.def"
yyterminate();
	YY_BREAK
	//--RULE------------------------------------------------------------------------------------------------
case 7:
#line 145 "definition\\RdrLexer.def"
return RdrParser::ID;
	YY_BREAK
case 8:
#line 146 "definition\\RdrLexer.def"
return RdrParser::IF;
	YY_BREAK
case 9:
#line 148 "definition\\RdrLexer.def"
return RdrParser::THEN;
	YY_BREAK
case 10:
#line 149 "definition\\RdrLexer.def"
return RdrParser::EXC;
	YY_BREAK
case 11:
#line 150 "definition\\RdrLexer.def"
return RdrParser::ENTWRD;
	YY_BREAK
case 12:
#line 152 "definition\\RdrLexer.def"
return RdrParser::LBRAC;
	YY_BREAK
case 13:
#line 153 "definition\\RdrLexer.def"
return RdrParser::RBRAC;
	YY_BREAK
case 14:
#line 154 "definition\\RdrLexer.def"
return RdrParser::TRANSF;
	YY_BREAK
case 15:
#line 156 "definition\\RdrLexer.def"

	YY_BREAK
case 16:
#line 158 "definition\\RdrLexer.def"
uStxVal->acVal = Str::norm(yytext); return RdrParser::STRING;
	YY_BREAK
case 17:
#line 159 "definition\\RdrLexer.def"
uStxVal->acVal = Str::norm(yytext); return RdrParser::STRING;
	YY_BREAK
case 18:
#line 160 "definition\\RdrLexer.def"
uStxVal->iVal = atoi((char *)yytext); return RdrParser::INT;
	YY_BREAK
case 19:
#line 162 "definition\\RdrLexer.def"
BEGIN COMMENT; return RdrParser::RULE_END;
	YY_BREAK
case 20:
#line 163 "definition\\RdrLexer.def"
iLine++; iColm=1; BEGIN COMMENT; return RdrParser::RULE_END;
	YY_BREAK
case YY_STATE_EOF(RULE):
#line 164 "definition\\RdrLexer.def"
BEGIN COMMENT; return RdrParser::RULE_END;
	YY_BREAK
case 22:
#line 166 "definition\\RdrLexer.def"
return RdrParser::ERROR;
	YY_BREAK
case 23:
#line 168 "definition\\RdrLexer.def"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
    yyterminate();
#line 496 "Q:\\01 Dokumenti\\IJS\\Projects\\LemmaGen\\support\\lex-bison\\binary\\win32\\flex\\flexskel.cc"

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yy___text - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &YY_Lexer_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yy___text + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yy___text + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
/* % code to do backtracking for compressed tables and set up yy_cp goes here */ 
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
#line 544 "Q:\\01 Dokumenti\\IJS\\Projects\\LemmaGen\\support\\lex-bison\\binary\\win32\\flex\\flexskel.cc"
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yy___text,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yy___text + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yy___text + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yy___text + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &YY_Lexer_CURRENT_BUFFER->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yy___text + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#if YY_Lexer_DEBUG != 0
#ifndef YY_Lexer_IOSTREAM
		fprintf(yy___stderr , "action # %d\n", yy_act );
#else
		yy___stderr <<"action # "<<(int)yy_act<<endl;
#endif
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
	yyterminate();/* avoid the no return value error message on MS-C7/dos */
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */
#ifndef YY_USE_CLASS
static int yy_get_next_buffer()
#else
int YY_Lexer_CLASS::yy_get_next_buffer()
#endif
    {
    register YY_Lexer_CHAR *dest = YY_Lexer_CURRENT_BUFFER->yy_ch_buf;
    register YY_Lexer_CHAR *source = yy___text - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &YY_Lexer_CURRENT_BUFFER->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yy___text;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( YY_Lexer_CURRENT_BUFFER->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = YY_Lexer_CURRENT_BUFFER->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&YY_Lexer_CURRENT_BUFFER->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move - YY_MORE_ADJ == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    YY_Lexer_CURRENT_BUFFER->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    YY_Lexer_CURRENT_BUFFER->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    YY_Lexer_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    YY_Lexer_CURRENT_BUFFER->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yy___text begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yy___text = &YY_Lexer_CURRENT_BUFFER->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

#ifndef YY_USE_CLASS
static yy_state_type yy_get_previous_state()
#else
long YY_Lexer_CLASS::yy_get_previous_state_()
#endif
    {
    register yy_state_type yy_current_state;
    register YY_Lexer_CHAR *yy_cp;

/* % code to get the start state into yy_current_state goes here */ 
    yy_current_state = yy_start;
#line 720 "Q:\\01 Dokumenti\\IJS\\Projects\\LemmaGen\\support\\lex-bison\\binary\\win32\\flex\\flexskel.cc"

    for ( yy_cp = yy___text + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
/* % code to find the next state goes here */ 
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 105 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
#line 724 "Q:\\01 Dokumenti\\IJS\\Projects\\LemmaGen\\support\\lex-bison\\binary\\win32\\flex\\flexskel.cc"
	}

#ifndef YY_USE_CLASS
    return ( yy_current_state );
#else
    return (long)( yy_current_state );
#endif
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif
#else
long YY_Lexer_CLASS::yy_try_NUL_trans_(long yy_current_state_)
#endif

    {
#ifndef YY_USE_CLASS
#else
    yy_state_type yy_current_state=(yy_state_type)yy_current_state_;
#endif
    register int yy_is_jam;
/* % code to find the next state, and perhaps do backtracking, goes here */ 
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 105 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 104);
#line 758 "Q:\\01 Dokumenti\\IJS\\Projects\\LemmaGen\\support\\lex-bison\\binary\\win32\\flex\\flexskel.cc"

#ifndef YY_USE_CLASS
    return ( yy_is_jam ? 0 : yy_current_state );
#else
    return (long)( yy_is_jam ? 0 : yy_current_state );
#endif
    }

#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
static void yyunput( YY_Lexer_CHAR c, register YY_Lexer_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_Lexer_CHAR c;
register YY_Lexer_CHAR *yy_bp;
#endif
#else
void YY_Lexer_CLASS::yyunput( YY_Lexer_CHAR c, YY_Lexer_CHAR *yy_bp )
#endif

    {
    register YY_Lexer_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yy___text */
    *yy_cp = yy_hold_char;

    if ( yy_cp < YY_Lexer_CURRENT_BUFFER->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_Lexer_CHAR *dest =
	    &YY_Lexer_CURRENT_BUFFER->yy_ch_buf[YY_Lexer_CURRENT_BUFFER->yy_buf_size + 2];
	register YY_Lexer_CHAR *source =
	    &YY_Lexer_CURRENT_BUFFER->yy_ch_buf[number_to_move];

	while ( source > YY_Lexer_CURRENT_BUFFER->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = YY_Lexer_CURRENT_BUFFER->yy_buf_size;

	if ( yy_cp < YY_Lexer_CURRENT_BUFFER->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yy___text again */
    }

#ifndef YY_USE_CLASS
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
#else
int YY_Lexer_CLASS::input()
#endif
    {
    int c;
    YY_Lexer_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &YY_Lexer_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yy___text = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yy___text + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;
#ifndef YY_USE_CLASS
#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yy___text + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifndef YY_USE_CLASS
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
#else
		    YY_FATAL_ERROR( "unexpected last match in YY_Lexer_CLASS::input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_Lexer_RESTART( YY_Lexer_IFILE  *input_file )
#else
void YY_Lexer_RESTART( input_file )
YY_Lexer_IFILE  *input_file;
#endif
#else
void YY_Lexer_CLASS::YY_Lexer_RESTART ( YY_Lexer_IFILE  *input_file )
#endif

    {
    YY_Lexer_INIT_BUFFER( YY_Lexer_CURRENT_BUFFER, input_file );
    YY_Lexer_LOAD_BUFFER_STATE();
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_Lexer_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer )
#else
void YY_Lexer_SWITCH_TO_BUFFER( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
#else
void YY_Lexer_CLASS::YY_Lexer_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer )
#endif

    {
    if ( YY_Lexer_CURRENT_BUFFER == new_buffer )
	return;

    if ( YY_Lexer_CURRENT_BUFFER )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	YY_Lexer_CURRENT_BUFFER->yy_buf_pos = yy_c_buf_p;
	YY_Lexer_CURRENT_BUFFER->yy_n_chars = yy_n_chars;
	}

    YY_Lexer_CURRENT_BUFFER = new_buffer;
    YY_Lexer_LOAD_BUFFER_STATE();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_Lexer_LOAD_BUFFER_STATE( void )
#else
void YY_Lexer_LOAD_BUFFER_STATE()
#endif
#else
void YY_Lexer_CLASS::YY_Lexer_LOAD_BUFFER_STATE(  )
#endif

    {
    yy_n_chars = YY_Lexer_CURRENT_BUFFER->yy_n_chars;
    yy___text = yy_c_buf_p = YY_Lexer_CURRENT_BUFFER->yy_buf_pos;
    yy___in = YY_Lexer_CURRENT_BUFFER->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE YY_Lexer_CREATE_BUFFER( YY_Lexer_IFILE  *file, int size )
#else
YY_BUFFER_STATE YY_Lexer_CREATE_BUFFER( file, size )
YY_Lexer_IFILE  *file;
int size;
#endif
#else
YY_BUFFER_STATE YY_Lexer_CLASS::YY_Lexer_CREATE_BUFFER( YY_Lexer_IFILE  *file, int size )
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in YY_Lexer_CREATE_BUFFER()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_Lexer_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in YY_Lexer_CREATE_BUFFER()" );

    YY_Lexer_INIT_BUFFER( b, file );

    return ( b );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_Lexer_DELETE_BUFFER( YY_BUFFER_STATE b )
#else
void YY_Lexer_DELETE_BUFFER( b )
YY_BUFFER_STATE b;
#endif
#else
void YY_Lexer_CLASS::YY_Lexer_DELETE_BUFFER( YY_BUFFER_STATE b )
#endif

    {
    if ( b == YY_Lexer_CURRENT_BUFFER )
	YY_Lexer_CURRENT_BUFFER = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_Lexer_INIT_BUFFER( YY_BUFFER_STATE b, YY_Lexer_IFILE  *file )
#else
void YY_Lexer_INIT_BUFFER( b, file )
YY_BUFFER_STATE b;
YY_Lexer_IFILE  *file;
#endif
#else
void YY_Lexer_CLASS::YY_Lexer_INIT_BUFFER( YY_BUFFER_STATE b, YY_Lexer_IFILE  *file)
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
#line 168 "definition\\RdrLexer.def"


void RdrLexer::debugPrt(const char *acToken, unsigned const char *acText, 
						const char *acOldState, const char *acNewState,
						const char *acReturn) {
	*yyout << "\tlexer:" << 
		" <" << acOldState << ">" <<
		" --> <" << acNewState << ">" <<
		" token{" << acToken << "}" <<
		" = \"" << (acText[0]!='\n' ? acText: (byte*) "\\n") << "\"" <<
		" return " << acReturn <<
		"\n";
}