name: C/C++ CI

on: [push]

jobs:
  build-on-gcc:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Create build directory
      run: mkdir -p build
    - name: Run CMake
      working-directory: build
      env:
        CXX: /usr/bin/gcc
        CC: /usr/bin/gcc
      run: cmake ..
    - name: Build
      working-directory: build
      run: make
    - name: Test
      working-directory: build
      run: make test
